version: '3'
services:
  akka-http-app:
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m
    # Run your app on a different port, not exposed to the host directly
    ports:
      - "8080"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - akka-http-app